name: Testing

on: [push]

jobs:
  build:
    if: false # temporarily disabled
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Create .env file
        run: |
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" > .env
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests
        run: |
          pytest
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
