name: lint

on: [push]

jobs:
  ruff-black-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --ignore-installed blinker
      - name: black check
        run: black --preview .
      - name: isort check
        run: isort --profile black .
